// pathlike/bindings.cpp — the `pygim.pathlike` pybind11 module.
//
// Exposes `path(...)` -> file(), a std::filesystem::path that reads and decodes
// itself with the engine its extension selects. The set of engines is OPEN:
// this file names none of them. It includes the generated type list
// (pathlike_engines.gen.h — setup.py globs adapter/engines/*.h, see
// ../engine_list.h) and every engine-dependent surface below is a fold over it:
// the typed classes, the docstrings, the error inventories, and the proofs.
//
// This is the single translation unit that instantiates rapidyaml's definitions,
// so RYML_SINGLE_HDR_DEFINE_NOW is defined *before* the amalgamated header is first
// included; every other include of it (from the engines) is a guarded no-op.

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "third_party/rapidyaml/ryml_all.hpp"

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#define PYBIND11_HAS_FILESYSTEM_IS_OPTIONAL
#include <pybind11/stl/filesystem.h>

#include <limits>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>

#include "../core.h"
#include "../engine_list.h"
#include "adapter.h"
#include "pathlike_engines.gen.h"   // GENERATED by setup.py: includes adapter/engines/*.h, defines Engines

#define STRINGIFY(x) #x
#define MACRO_STRINGIFY(x) STRINGIFY(x)

namespace py = pybind11;
using namespace pygim::pathlike;

// ── The registry is proven on every build ──────────────────────────────────
// A descriptor without load()/write() fails in all_implemented() naming the
// descriptor; a duplicate extension/selector, a malformed name/extension, or a
// selector that does not resolve to its engine fails holds(). Under C++26 the
// message IS the conflict ("'.json' is claimed by both 'json' and 'csv'").
static_assert(Engines::size > 0, "pathlike: no engines discovered (adapter/engines/ is empty?)");

static_assert(all_implemented(Engines{}), "every pathlike engine must provide static load() and write()");
#if defined(__cpp_static_assert) && __cpp_static_assert >= 202306L
static_assert(Engines::holds(), Engines::conflict_report());
#else
static_assert(Engines::holds(), "pathlike engine registry invariants violated: duplicate extension or "
                                "selector, malformed name/extension, or a selector that does not resolve "
                                "to its engine (build with -std=c++26 to see which)");
#endif
#if PYGIM_PATHLIKE_REFLECTION
// With P2996 reflection (GCC 16, -freflection) the compiler enumerates the
// engine structs itself: the generated list must be exactly that set, and
// every engine must be named after its struct.
static_assert(std::is_same_v<Engines, reflected_engines_t<engine_list>>,
              "the generated engine list (setup.py glob of adapter/engines/*.h) and the engine "
              "structs the compiler sees in namespace pygim::pathlike::engines disagree");
static_assert(names_match_identifiers(Engines{}),
              "every engine's info.name must equal its struct name (== its file stem)");
#endif

namespace {

// None or "" -> auto (nullptr); a known selector -> its engine; else throws.
const engine_info* engine_from_arg(const std::optional<std::string>& name) {
    if (!name || name->empty()) return nullptr;
    if (const engine_info* e = Engines::from_name_at_runtime(*name)) return e;
    throw std::invalid_argument("unknown engine: '" + *name + "' (known: " + Engines::known_text() + ")");
}

std::string_view requested(const std::optional<std::string>& engine) {
    return engine ? std::string_view(*engine) : std::string_view{};
}

// key_cache: -1 -> unbounded, 0 -> off, N -> at most N distinct interned keys.
std::size_t cache_capacity_from_arg(py::ssize_t key_cache) {
    if (key_cache < 0) return std::numeric_limits<std::size_t>::max();
    return static_cast<std::size_t>(key_cache);
}

// The path as a Python str, decoded from the NATIVE representation.
py::str fspath_str(const file& f) {
#ifdef _WIN32
    return py::cast(f.path().native());   // std::wstring -> str, lossless
#else
    const std::string& n = f.path().native();
    return py::reinterpret_steal<py::str>(
        PyUnicode_DecodeFSDefaultAndSize(n.data(), static_cast<py::ssize_t>(n.size())));
#endif
}

py::object wrap(file f) { return pygim::pathlike::wrap(Engines{}, std::move(f)); }

// TEMPORARY (bisect variant 9): path() as a named function instead of a lambda.
py::object path_factory(fs::path p, const std::optional<std::string>& engine) {
    return wrap(file(std::move(p), engine_from_arg(engine)));
}

py::list wrap_all(std::vector<file> files) {
    py::list out;
    for (file& f : files) out.append(wrap(std::move(f)));
    return out;
}

// ── Docstrings derived from the registry (static storage: pybind11 keeps pointers).
// Passed as py::doc(...) rather than a bare const char*: a dynamic docstring as
// a bare pointer in module_::def's extras pack crashed MSVC (C1001).
std::string join_exts(const engine_info& e, std::string_view sep) {
    std::string s;
    for (std::string_view x : e.exts) {
        if (!s.empty()) s += sep;
        s += "``" + std::string(x) + "``";
    }
    return s;
}

// The docstring fragments are folds over the pack through plain function
// templates (the same portable construct set as adapter.h: no capturing
// generic lambdas at run time).
template <class E>
void append_dispatch(std::string& out) {
    if (!out.empty()) out += "; ";
    out += join_exts(E::info, "/") + " -> " + std::string(E::info.name) + " (" + std::string(E::info.label) + ")";
}
template <class E>
void append_label(std::string& out) {
    if (!out.empty()) out += "/";
    out += "'" + std::string(E::info.label) + "'";
}
template <class E>
void append_name(std::string& out) {
    if (!out.empty()) out += "/";
    out += std::string(E::info.name);
}
template <class E>
void append_note(std::string& out) {
    out += "\n- " + std::string(E::info.name) + ": " + std::string(E::info.doc);
}

template <class... Es> std::string dispatch_sentence_of(engine_list<Es...>) { std::string out; (append_dispatch<Es>(out), ...); return out; }
template <class... Es> std::string labels_list_of(engine_list<Es...>) { std::string out; (append_label<Es>(out), ...); return out; }
template <class... Es> std::string names_list_of(engine_list<Es...>) { std::string out; (append_name<Es>(out), ...); return out; }
template <class... Es> std::string engine_notes_of(engine_list<Es...>) { std::string out; (append_note<Es>(out), ...); return out; }

// "``.json`` -> json (simdjson); ``.jsonl``/``.ndjson`` -> jsonl (simdjson-ndjson); ..."
const std::string& dispatch_sentence() {
    static const std::string s = dispatch_sentence_of(Engines{});
    return s;
}

// "'rapidyaml'/'simdjson'/..." — every label, in pack order.
const std::string& labels_list() {
    static const std::string s = labels_list_of(Engines{});
    return s;
}

// "yaml/json/toml/jsonl" — every format name, in pack order.
const std::string& names_list() {
    static const std::string s = names_list_of(Engines{});
    return s;
}

// "- json: <doc>\n- jsonl: <doc>\n..." — every engine's own sentence.
const std::string& engine_notes() {
    static const std::string s = engine_notes_of(Engines{});
    return s;
}

const std::string& file_doc() {
    static const std::string s =
        "A filesystem path that knows how to read and decode itself.\n\n"
        "Never constructed directly — use ``pygim.path(...)``. The decoding engine is chosen\n"
        "at compile time from the extension (" + dispatch_sentence() + "); pin one with\n"
        "``engine=`` at construction, or override per call with ``read(engine=...)``.\n"
        "Implements ``os.PathLike``, so it drops into ``open()``, ``Path()``, etc.\n\n"
        "Engines (one header each under adapter/engines/, discovered by the build):" + engine_notes() + "\n";
    return s;
}

const std::string& engine_doc() {
    static const std::string s =
        "The engine (library) read()/write() will use — the constructor pin, else the extension (" +
        labels_list() + ") — or None when neither resolves.";
    return s;
}

const std::string& read_doc() {
    static const std::string s =
        "Decode the file to native Python objects (I/O and parsing release the GIL). engine= overrides "
        "for this call (" + names_list() + ", a library label, or an alias); key_cache bounds the "
        "key-interning cache (0 off, -1 unbounded).";
    return s;
}

const std::string& write_doc() {
    static const std::string s =
        "Serialise obj to this path with the resolved engine (" + names_list() + "). Strings that would "
        "read back typed are quoted automatically, so write/read round-trips. Format constraints are the "
        "engine's own:" + engine_notes() + "\n";
    return s;
}

const std::string& path_doc() {
    static const std::string s =
        "Wrap a path in a self-reading, self-decoding file() — typed as the engine's ``<name>file`` "
        "class when an engine resolves. Pass engine= to pin the decoder (" + names_list() +
        ", a library label, or an alias); default resolves from the extension. Known engines: " +
        Engines::known_text() + ".";
    return s;
}

}  // namespace

PYBIND11_MODULE(pathlike, m) {
    m.doc() = "path(): an os.PathLike that reads & decodes itself with the optimal engine.";

    py::class_<file>(m, "file", file_doc().c_str())   // class docs take a bare const char* (py::doc is for functions)
        .def(py::init([](fs::path p, const std::optional<std::string>& engine) {
                 return file(std::move(p), engine_from_arg(engine));
             }),
             py::arg("path"), py::arg("engine") = py::none())
        .def_property_readonly(
            "engine",
            [](const file& f) -> py::object {
                const engine_info* e = Engines::resolved(f);
                if (!e) return py::none();
                return py::str(std::string(e->label));
            },
            py::doc(engine_doc().c_str()))
        // Decode the NATIVE path representation (wstring on Windows — lossless;
        // bytes via the filesystem encoding on POSIX). fs::path::string() would
        // narrow through the ACP on Windows and can mangle non-ASCII paths.
        .def("__fspath__", [](const file& f) { return fspath_str(f); },
             "os.PathLike protocol: the plain path string.")
        .def("__repr__", &file::repr)
        .def("__str__", [](const file& f) { return fspath_str(f); })
        .def("__eq__",
             [](const file& a, const file& b) { return a.path() == b.path(); },
             py::is_operator())
        .def("__hash__", [](const file& f) { return py::hash(py::cast(f.fspath())); })
        .def_property_readonly("uri", &file::uri, "The 'file://<path>' URI form.")
        // -- name components (case preserved, like pathlib) --
        .def_property_readonly("name", &file::name, "The final path component.")
        .def_property_readonly("stem", &file::stem, "The final component without its suffix.")
        .def_property_readonly("suffix", &file::suffix, "The final extension incl. dot ('.yaml').")
        .def_property_readonly("suffixes", &file::suffixes,
                               "All extensions of the final component ('.tar.gz' -> ['.tar','.gz']).")
        .def_property_readonly("parts", &file::parts, "The path components as a list.")
        // -- composition: path / "sub" / "file.yaml" --
        .def("__truediv__", [](const file& f, const fs::path& other) { return wrap(f.joined(other)); },
             py::is_operator())
        .def("__rtruediv__", [](const file& f, const fs::path& other) { return wrap(f.rjoined(other)); },
             py::is_operator())
        .def("joinpath",
             [](const file& f, const py::args& parts) {
                 file out = f;
                 for (const py::handle& part : parts) out = out.joined(part.cast<fs::path>());
                 return wrap(std::move(out));
             },
             "Append one or more path components, like pathlib's joinpath().")
        .def_property_readonly("parent", [](const file& f) { return wrap(f.parent()); },
                               "The parent directory as a file().")
        .def_property_readonly("parents", [](const file& f) { return wrap_all(f.parents()); },
                               "Ancestor directories, closest first.")
        // -- derived paths (return new file()s) --
        .def("with_suffix", [](const file& f, const std::string& s) { return wrap(f.with_suffix(s)); },
             py::arg("suffix"), "A copy with the final suffix replaced.")
        .def("with_name", [](const file& f, const std::string& n) { return wrap(f.with_name(n)); },
             py::arg("name"), "A copy with the final component replaced.")
        .def("with_stem", [](const file& f, const std::string& s) { return wrap(f.with_stem(s)); },
             py::arg("stem"), "A copy with the stem replaced (suffix kept).")
        .def("absolute", [](const file& f) { return wrap(f.absolute()); },
             "An absolute copy (does not resolve symlinks/..).")
        .def("resolve", [](const file& f) { return wrap(f.resolve()); },
             "A canonical, absolute copy (resolves symlinks/..).")
        // -- filesystem status --
        .def("is_absolute", &file::is_absolute, "Whether the path is absolute.")
        .def("exists", &file::exists, "Whether the path exists on disk.")
        .def("is_file", &file::is_file, "Whether it is a regular file.")
        .def("is_dir", &file::is_dir, "Whether it is a directory.")
        .def("is_symlink", &file::is_symlink, "Whether it is a symbolic link.")
        .def("size", &file::size, "File size in bytes (raises if it does not exist).")
        .def("read_bytes", [](const file& f) { return py::bytes(f.read_bytes()); },
             "The raw file bytes, undecoded.")
        .def("write_bytes",
             [](const file& f, py::bytes data) {
                 const std::string_view sv = data;
                 py::gil_scoped_release nogil;
                 f.write_bytes(sv);
             },
             py::arg("data"), "Replace the file's contents with the given bytes.")
        .def("mkdir", &file::mkdir, py::arg("parents") = false, py::arg("exist_ok") = false,
             "Create this directory, like pathlib: parents= creates missing ancestors, "
             "exist_ok= tolerates an existing directory.")
        .def("read",
             [](const file& f, const std::optional<std::string>& engine, py::ssize_t key_cache) {
                 return load(Engines{}, Engines::resolve(f, requested(engine)), f,
                             cache_capacity_from_arg(key_cache));
             },
             py::arg("engine") = py::none(), py::arg("key_cache") = 256, py::doc(read_doc().c_str()))
        .def("write",
             [](const file& f, py::handle obj, const std::optional<std::string>& engine) {
                 write(Engines{}, Engines::resolve(f, requested(engine)), f, obj);
             },
             py::arg("obj"), py::arg("engine") = py::none(), py::doc(write_doc().c_str()))
        // -- directory traversal (results inherit the engine pin) --
        .def("iterdir", [](const file& f) { return wrap_all(f.iterdir()); },
             "The directory's children, sorted.")
        .def("glob", [](const file& f, std::string_view p) { return wrap_all(f.glob(p)); },
             py::arg("pattern"),
             "Relative glob: * and ? within a component, ** across directories. "
             "Sorted and deduplicated; results inherit the engine pin.")
        .def("rglob", [](const file& f, std::string_view p) { return wrap_all(f.rglob(p)); },
             py::arg("pattern"),
             "glob('**/' + pattern): the pattern anywhere under this directory.")
        .def("pathset",
             [](const file& f, const std::string& pattern) {
                 std::vector<std::string> paths;
                 for (const file& m : f.glob(pattern)) paths.push_back(m.fspath());
                 return py::module_::import("pygim.pathset").attr("PathSet")(paths);
             },
             py::arg("pattern") = std::string("*"),
             "The glob results as a pygim.pathset.PathSet, for set algebra and "
             "Filter queries.");

// TEMPORARY (PR #21 MSVC C1001 bisect) — variants of the block below, one per
// Windows CI job (PYGIM_ICE_VARIANT = Python minor version); 12 is the control.
#ifndef PYGIM_ICE_VARIANT
#define PYGIM_ICE_VARIANT 12
#endif
#if PYGIM_ICE_VARIANT != 14
    // One typed subclass per engine ("<name>file"); constructing one pins its engine.
    bind_typed(Engines{}, m);
#endif

#if PYGIM_ICE_VARIANT == 9
    m.def("path", &path_factory, py::arg("path"), py::arg("engine") = py::none(), py::doc(path_doc().c_str()));
#elif PYGIM_ICE_VARIANT == 10
    m.def("path",
          [](fs::path p, const std::optional<std::string>& engine) {
              return py::cast(file(std::move(p), engine_from_arg(engine)));   // no wrap()
          },
          py::arg("path"), py::arg("engine") = py::none(), py::doc(path_doc().c_str()));
#elif PYGIM_ICE_VARIANT == 11
    m.def("path",
          [](fs::path p, const std::optional<std::string>&) {
              return wrap(file(std::move(p)));   // no engine_from_arg()
          },
          py::arg("path"), py::arg("engine") = py::none(), py::doc(path_doc().c_str()));
#elif PYGIM_ICE_VARIANT == 13
    // no path() at all
#else
    m.def("path",
          [](fs::path p, const std::optional<std::string>& engine) {
              return wrap(file(std::move(p), engine_from_arg(engine)));
          },
          py::arg("path"), py::arg("engine") = py::none(), py::doc(path_doc().c_str()));
#endif

#if PYGIM_ICE_VARIANT != 14
    // The registry, introspectable: a tuple of EngineInfo(name, label, extensions, aliases, doc).
    m.attr("ENGINES") = engines_record(Engines{});
#endif

#ifndef VERSION_INFO
#error "VERSION_INFO must be defined by the build system (setup.py base_macros)"
#endif
    m.attr("__version__") = MACRO_STRINGIFY(VERSION_INFO);
}
