// pathlike/bindings.cpp — the `pygim.pathlike` pybind11 module.
//
// Exposes `path(...)` -> file(), a std::filesystem::path that reads and decodes
// itself with the engine its extension selects. The set of engines is OPEN:
// this file names none of them. It includes the generated type list
// (pathlike_engines.gen.h — setup.py globs adapter/engines/*.h, see
// ../engine_list.h) and every engine-dependent surface below is a fold over it:
// the typed classes, the docstrings, the error inventories, and the proofs.
//
// This is the single translation unit that instantiates rapidyaml's definitions,
// so RYML_SINGLE_HDR_DEFINE_NOW is defined *before* the amalgamated header is first
// included; every other include of it (from the engines) is a guarded no-op.

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "third_party/rapidyaml/ryml_all.hpp"

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#define PYBIND11_HAS_FILESYSTEM_IS_OPTIONAL
#include <pybind11/stl/filesystem.h>

#include <limits>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>

#include "../core.h"
#include "../engine_list.h"
#include "adapter.h"
#include "path_store.h"
#include "pathset.h"
#include "pathview.h"
#include "pathlike_engines.gen.h"   // GENERATED by setup.py: includes adapter/engines/*.h, defines Engines

#define STRINGIFY(x) #x
#define MACRO_STRINGIFY(x) STRINGIFY(x)

namespace py = pybind11;
using namespace pygim::pathlike;

// ── The registry is proven on every build ──────────────────────────────────
// A descriptor without load()/write() fails in all_implemented() naming the
// descriptor; a duplicate extension/selector, a malformed name/extension, or a
// selector that does not resolve to its engine fails holds(). Under C++26 the
// message IS the conflict ("'.json' is claimed by both 'json' and 'csv'").
static_assert(Engines::size > 0, "pathlike: no engines discovered (adapter/engines/ is empty?)");

static_assert(all_implemented(Engines{}), "every pathlike engine must provide static load() and write()");
#if defined(__cpp_static_assert) && __cpp_static_assert >= 202306L
static_assert(Engines::holds(), Engines::conflict_report());
#else
static_assert(Engines::holds(), "pathlike engine registry invariants violated: duplicate extension or "
                                "selector, malformed name/extension, or a selector that does not resolve "
                                "to its engine (build with -std=c++26 to see which)");
#endif
#if PYGIM_PATHLIKE_REFLECTION
// With P2996 reflection (GCC 16, -freflection) the compiler enumerates the
// engine structs itself: the generated list must be exactly that set, and
// every engine must be named after its struct.
static_assert(std::is_same_v<Engines, reflected_engines_t<engine_list>>,
              "the generated engine list (setup.py glob of adapter/engines/*.h) and the engine "
              "structs the compiler sees in namespace pygim::pathlike::engines disagree");
static_assert(names_match_identifiers(Engines{}),
              "every engine's info.name must equal its struct name (== its file stem)");
#endif

// End to end, at compile time: a path named with each engine's extension —
// given as native text and as a file URI — dispatches to that engine
// (`file` is a literal type; the tables are built transiently).
template <class E>
consteval bool dispatches_to() {
    for (std::string_view x : E::info.exts) {
        const file native("dir/name" + std::string(x));
        const file via_uri("file:///C:/dir/name" + std::string(x));   // absolute under both strategies (a drive on Windows)
        if (Engines::for_ext(native.ext_key()) != &E::info || Engines::resolved_ct(via_uri) != &E::info) return false;
    }
    return true;
}
template <class... Es>
consteval bool paths_dispatch_to_their_engines(engine_list<Es...>) { return (dispatches_to<Es>() && ... && true); }
static_assert(paths_dispatch_to_their_engines(Engines{}));

namespace {

// None or "" -> auto (nullptr); a known selector -> its engine; else throws.
const engine_info* engine_from_arg(std::string_view name) {
    if (name.empty()) return nullptr;
    if (const engine_info* e = Engines::from_name_at_runtime(name)) return e;
    throw std::invalid_argument("unknown engine: '" + std::string(name) + "' (known: " + Engines::known_text() + ")");
}
const engine_info* engine_from_arg(const std::optional<std::string>& name) {
    return engine_from_arg(name ? std::string_view(*name) : std::string_view{});
}
// ── Docstrings derived from the registry (static storage: pybind11 keeps pointers).
// Passed as py::doc(...) rather than a bare const char*: a dynamic docstring as
// a bare pointer in module_::def's extras pack crashed MSVC (C1001).
std::string join_exts(const engine_info& e, std::string_view sep) {
    detail::text t;
    for (std::string_view x : e.exts) {
        detail::separate(t, sep);
        t.put("``");
        t.put(x);
        t.put("``");
    }
    return std::move(t.out);
}

// The docstring fragments are folds over the pack through plain function
// templates (the same portable construct set as adapter.h: no capturing
// generic lambdas at run time), writing into engine_list.h's text sink.
template <class E>
void append_dispatch(detail::text& t) {
    detail::separate(t, "; ");
    t.put(join_exts(E::info, "/"));
    t.put(" -> ");
    t.put(E::info.name);
    t.put(" (");
    t.put(E::info.label);
    t.put(")");
}
template <class E>
void append_label(detail::text& t) {
    detail::separate(t, "/");
    t.put("'");
    t.put(E::info.label);
    t.put("'");
}
template <class E>
void append_name(detail::text& t) {
    detail::separate(t, "/");
    t.put(E::info.name);
}
template <class E>
void append_note(detail::text& t) {
    t.put("\n- ");
    t.put(E::info.name);
    t.put(": ");
    t.put(E::info.doc);
}

template <class... Es> std::string dispatch_sentence_of(engine_list<Es...>) { detail::text t; (append_dispatch<Es>(t), ...); return std::move(t.out); }
template <class... Es> std::string labels_list_of(engine_list<Es...>) { detail::text t; (append_label<Es>(t), ...); return std::move(t.out); }
template <class... Es> std::string names_list_of(engine_list<Es...>) { detail::text t; (append_name<Es>(t), ...); return std::move(t.out); }
template <class... Es> std::string engine_notes_of(engine_list<Es...>) { detail::text t; (append_note<Es>(t), ...); return std::move(t.out); }

// "``.json`` -> json (simdjson); ``.jsonl``/``.ndjson`` -> jsonl (simdjson-ndjson); ..."
const std::string& dispatch_sentence() {
    static const std::string s = dispatch_sentence_of(Engines{});
    return s;
}

// "'rapidyaml'/'simdjson'/..." — every label, in pack order.
const std::string& labels_list() {
    static const std::string s = labels_list_of(Engines{});
    return s;
}

// "yaml/json/toml/jsonl" — every format name, in pack order.
const std::string& names_list() {
    static const std::string s = names_list_of(Engines{});
    return s;
}

// "- json: <doc>\n- jsonl: <doc>\n..." — every engine's own sentence.
const std::string& engine_notes() {
    static const std::string s = engine_notes_of(Engines{});
    return s;
}

const std::string& file_doc() {
    static const std::string s =
        "A filesystem path that knows how to read and decode itself: a handle on a row of a path\n"
        "table (every distinct component stored once). The decoding engine is chosen\n"
        "from the extension (" + dispatch_sentence() + "), and ``path(\"x.yaml\")`` is a ``yamlpath``;\n"
        "pin one with ``engine=`` at construction, or override per call with ``read(engine=...)``.\n"
        "``store=`` chooses the table (a PathStore) the path and everything derived from it live in.\n"
        "Implements ``os.PathLike``, so it drops into ``open()``, ``Path()``, etc.\n\n"
        "Path semantics follow pathlib (str() is the normalised spelling: ``a//b/`` -> ``a/b``);\n"
        "``file://`` URIs are accepted as input (RFC 8089, decoded like ``Path.from_uri``) and\n"
        "``.uri`` renders an absolute path per RFC 3986 (``file:///a%20b``).\n\n"
        "Engines (one header each under adapter/engines/, discovered by the build):" + engine_notes() + "\n";
    return s;
}

const std::string& engine_doc() {
    static const std::string s =
        "The engine (library) read()/write() will use — the constructor pin, else the extension (" +
        labels_list() + ") — or None when neither resolves.";
    return s;
}

const std::string& read_doc() {
    static const std::string s =
        "Decode the file to native Python objects (I/O and parsing release the GIL). engine= overrides "
        "for this call (" + names_list() + ", a library label, or an alias); key_cache bounds the "
        "key-interning cache (0 off, -1 unbounded).";
    return s;
}

const std::string& write_doc() {
    static const std::string s =
        "Serialise obj to this path with the resolved engine (" + names_list() + "). Strings that would "
        "read back typed are quoted automatically, so write/read round-trips. Format constraints are the "
        "engine's own:" + engine_notes() + "\n";
    return s;
}

}  // namespace

PYBIND11_MODULE(pathlike, m) {
    m.doc() = "path(): an os.PathLike that reads & decodes itself with the optimal engine.";
    filesystem_is_utf8() = py::module_::import("sys").attr("getfilesystemencoding")().cast<std::string>() == "utf-8";

    bind_path_store(m);   // PathStore, default_store() (path_store.h)
    const path_docs docs{file_doc(), engine_doc(), read_doc(), write_doc()};
    py::class_<pathview> path_cls = bind_path(Engines{}, m, docs);   // path + <engine>path classes (pathview.h)
    bind_pathset(Engines{}, m, path_cls);                            // PathSet, Filter, Query (pathset.h)

    // The registry, introspectable: a tuple of EngineInfo(name, label, extensions, aliases, doc).
    m.attr("ENGINES") = engines_record(Engines{});

#ifndef VERSION_INFO
#error "VERSION_INFO must be defined by the build system (setup.py base_macros)"
#endif
    m.attr("__version__") = MACRO_STRINGIFY(VERSION_INFO);
}
