import pygim.exceptions as ex
from pygim.typing import AnyClass, AnyCallable,
from _typeshed import Incomplete
from typing import *

class EntangledError(ex.GimError): ...
class EntangledClassError(EntangledError): ...
class EntangledMethodError(EntangledError): ...

class EntangledClassMetaMeta(type):
    __namespace: Dict[]
    def __call__(self, class_name: Text, bases: Tuple[AnyClass], namespace: Dict[Text, Any], namespace_name: Text = ...) -> Any: ...  # type: ignore[override]

class EntangledClassMeta(type, metaclass=EntangledClassMetaMeta):
    @classmethod
    def __prepare__(cls, name, bases): ...
    def __new__(mcls: AnyClass, name: Text, bases: Tuple[AnyClass], namespace: Dict[Text, Any]) -> Any: ...
    def __getitem__(self, key: Hashable) -> Any: ...
    def __call__(self, *args: Any, **kwds: Any) -> Any: ...

class EntangledClass(metaclass=EntangledClassMeta):
    def namespace(cls) -> Text: ...
