from _typeshed import Incomplete
from typing import Any, Iterable, Iterator, Optional, Sequence, Tuple, TypeVar, Union
from pygim.gimmicks import gim_type, gimmick

class RangeSelectorMeta(gim_type):
    def __call__(cls, ranges, labels: Incomplete | None = ...) -> None: ...


class RangeSelector(gimmick, metaclass=RangeSelectorMeta):
    def __post_init__(self) -> None: ...
    def __getitem__(self, index: Union[int, Tuple, slice]) -> Union[str, Tuple, list]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator: ...
    def __reversed__(self) -> None: ...
    def __contains__(self, value): ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    def find(self, value) -> Tuple[int, int]: ...
    def select(self, input_value, *, default=...): ...
    def __init__(self, *, _ranges) -> None: ...
