"""Problem-space memory: retrieval driven by the kind of problem being solved.

A repository is a folder of plain files — a vocabulary, content objects and a
hash-chained audit log — shared through git. Every operation returns a plain
dict; a refused write is a result with ``"refused"`` and ``"facts"``, not an
exception. The design is docs/design/memory/.
"""
from typing import Any, Dict, List, Sequence

def digest(data: bytes) -> str:
    """The 128-bit digest pygim.memory names content by, as 32 hex characters."""

class VocabularyError(ValueError):
    """The vocabulary files do not load; the message lists every failure by file and line."""

class Memory:
    def __init__(self, root: str) -> None: ...
    @staticmethod
    def init(root: str) -> None: ...
    @property
    def root(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def head(self) -> str: ...
    def refresh(self) -> None: ...
    def session(self) -> Dict[str, Any]: ...
    def vocabulary(self) -> Dict[str, Any]: ...
    def read(self, hard: Sequence[str], soft: Sequence[str] = ..., *, max: int = 8, budget: int = 0,
             session: int = 0) -> Dict[str, Any]: ...
    def remember(self, *, title: str, text: str, tags: Sequence[str], reason: str = "",
                 supersedes: Sequence[str] = ..., generalises: Sequence[str] = ..., seen: Sequence[str] = ...,
                 cites: Sequence[str] = ..., proposals: List[Dict[str, str]] = ..., session: int = 0, turn: int = 0,
                 author: str = "agent") -> Dict[str, Any]: ...
    def review(self, session: int) -> Dict[str, Any]: ...
    def accept(self, memory: str, *, reason: str = "", author: str = "human") -> Dict[str, Any]: ...
    def lessons(self, session: int, text: str, *, author: str = "agent") -> Dict[str, Any]: ...
    def merge(self, memories: Sequence[str], *, title: str, text: str, reason: str, tags: Sequence[str] = ...,
              session: int = 0, author: str = "agent") -> Dict[str, Any]: ...
    def learn(self, memory: str, *, tag: str = "", reason: str = "", session: int = 0) -> Dict[str, Any]: ...
    def link(self, memory: str, tag: str, *, reason: str, author: str = "human") -> Dict[str, Any]: ...
    def unlink(self, memory: str, tag: str, *, reason: str, author: str = "human") -> Dict[str, Any]: ...
    def retire(self, memory: str, *, reason: str, author: str = "human") -> Dict[str, Any]: ...
    def show(self, memory: str) -> Dict[str, Any]: ...
    def proposals(self) -> List[Dict[str, Any]]: ...
    def ingest(self, path: str) -> Dict[str, Any]: ...
    def receipts(self) -> List[Dict[str, Any]]: ...
    def rerun(self, receipt: Dict[str, Any]) -> Dict[str, Any]: ...
