"""Type stubs for pygim.pathlike.

The compiled extension is untyped at runtime; this stub documents the stable
public contract of ``pygim.path``: one class, a handle on a row of a path table.

The engine set is OPEN (one C++ header per engine, discovered by the build), so
everything engine-dependent — the ``Engine`` selector literal, the
``<name>path`` typed classes and ``ENGINES`` — lives in the generated block at
the end, rendered from the built module by ``pygim stubs`` and kept current by
a test.
"""

import os
from typing import Any, Iterable, Iterator, Literal, NamedTuple, overload

PathLike = str | bytes | os.PathLike[str] | path


class path(os.PathLike[str]):
    """A filesystem path that reads and decodes itself: a handle (table, row) on a
    PathStore's table, where every distinct component is stored once. ``path("x.yaml")``
    is a ``yamlpath`` (the typed class of the engine its extension resolves to);
    ``engine=`` pins one; ``store=`` chooses the table this path and everything derived
    from it live in (default: ``default_store()``). Equal paths compare and hash alike
    whatever their spelling; two handles are not promised to be the same object."""
    def __init__(self, path: str | bytes | os.PathLike[str], engine: Engine | None = None,
                 *, store: PathStore | None = None) -> None: ...

    # -- decoding / encoding ------------------------------------------------
    def read(self, engine: Engine | None = None, key_cache: int = 256) -> Any:
        """Decode the file to native Python objects (GIL released during I/O
        and parsing). ``key_cache`` bounds key interning: 0 off, -1 unbounded."""
    def write(self, obj: Any, engine: Engine | None = None) -> None:
        """Serialise ``obj`` with the resolved engine. Strings that would read
        back typed are quoted, so write/read round-trips. Format constraints are
        the engine's own (see each ``<name>path`` docstring)."""
    def read_bytes(self) -> bytes: ...
    def write_bytes(self, data: bytes) -> None:
        """Replace the file's contents with *data*, byte for byte."""
    def mkdir(self, parents: bool = False, exist_ok: bool = False) -> None:
        """Create this directory, with pathlib's parents/exist_ok semantics."""

    @property
    def engine(self) -> str | None:
        """The library label read()/write() will use ('rapidyaml', 'simdjson', ...):
        the constructor pin, else the extension — or None when neither resolves."""
    @property
    def store(self) -> PathStore:
        """The store (table) this path lives in; derived paths share it."""

    # -- os.PathLike / identity ---------------------------------------------
    def __fspath__(self) -> str:
        """The native path text in pathlib's normalised spelling ('a//b/' -> 'a/b')."""
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

    # -- name components (pathlib parity), read from the table ---------------
    @property
    def uri(self) -> str:
        """An absolute path as an RFC 3986 file URI (percent-encoded: 'file:///a%20b',
        'file://host/share/x'); a relative path keeps the 'file://<path>' spelling."""
    @property
    def name(self) -> str: ...
    @property
    def stem(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def suffixes(self) -> list[str]: ...
    @property
    def parts(self) -> list[str]: ...
    @property
    def depth(self) -> int:
        """Named components below the anchor."""

    # -- composition / derived paths (results share the table and inherit the pin) --
    def __truediv__(self, other: str | bytes | os.PathLike[str]) -> path: ...
    def __rtruediv__(self, other: str | bytes | os.PathLike[str]) -> path: ...
    def joinpath(self, *parts: str | bytes | os.PathLike[str]) -> path: ...
    @property
    def parent(self) -> path: ...
    @property
    def parents(self) -> list[path]: ...
    def with_suffix(self, suffix: str) -> path: ...
    def with_name(self, name: str) -> path: ...
    def with_stem(self, stem: str) -> path: ...
    def absolute(self) -> path: ...
    def resolve(self) -> path: ...

    # -- filesystem status --------------------------------------------------
    def is_absolute(self) -> bool: ...
    def exists(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def is_symlink(self) -> bool: ...
    def size(self) -> int: ...

    # -- directory traversal ------------------------------------------------
    def iterdir(self) -> list[path]: ...
    def glob(self, pattern: str) -> list[path]: ...
    def rglob(self, pattern: str) -> list[path]: ...
    def pathset(self, pattern: str = "*") -> PathSet:
        """The glob results as a PathSet over this path's table."""


class EngineInfo(NamedTuple):
    """One entry of ``ENGINES``: the registry as data."""
    name: str
    label: str
    extensions: tuple[str, ...]
    aliases: tuple[str, ...]
    doc: str

class PathSet:
    """Many paths as ONE table (prototype): every distinct component stored once, every
    path a (parent, name) row. Iterating yields path objects over the table; scan() reuses one.
    Filters and |, &, - return sets sharing the table; to_list() renders the members."""
    def __init__(self, paths: PathLike | Iterable[PathLike] | None = None,
                 *, store: PathStore | None = None) -> None: ...
    @staticmethod
    def cwd() -> PathSet: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def clone(self) -> PathSet: ...
    def add(self, path: PathLike) -> None: ...
    def extend(self, paths: Iterable[PathLike]) -> None: ...
    def reserve(self, n: int) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, path: object) -> bool: ...
    def __iter__(self) -> Iterator[path]: ...
    def scan(self) -> Iterator[path]:
        """Iterate reusing ONE plain path object (its row advances): no allocation per element."""
    def __getitem__(self, i: int) -> path: ...
    def filter_suffix(self, suffix: str) -> PathSet: ...
    def filter_name(self, glob: str) -> PathSet: ...
    def filter_absolute(self) -> PathSet: ...
    def filter(self, filter: Filter) -> PathSet: ...
    @overload
    def __or__(self, other: PathSet) -> PathSet: ...
    @overload
    def __or__(self, other: Filter) -> Query: ...
    @overload
    def __and__(self, other: PathSet) -> PathSet: ...
    @overload
    def __and__(self, other: Filter) -> Query: ...
    def __sub__(self, other: PathSet | PathLike | Iterable[PathLike]) -> PathSet: ...
    def __add__(self, other: PathSet | PathLike | Iterable[PathLike]) -> PathSet: ...
    def read_all_files(self) -> list[str]: ...
    def count_union(self, other: PathSet) -> int: ...
    def count_intersection(self, other: PathSet) -> int: ...
    def count_difference(self, other: PathSet) -> int: ...
    def to_list(self) -> list[str]: ...
    def stats(self) -> dict[str, int]: ...


class Filter:
    """A predicate over the paths of a PathSet (ext(), name(), absolute()) with & | ~;
    apply with `ps & f` (a lazy Query) or ps.filter(f). Reads the table, never the filesystem."""
    def __and__(self, other: Filter) -> Filter: ...
    def __or__(self, other: Filter) -> Filter: ...
    def __invert__(self) -> Filter: ...


class Query:
    """A lazy filter over a PathSet (`ps & f`): & narrows, | widens, eval() runs it."""
    def __and__(self, other: Filter) -> Query: ...
    def __or__(self, other: Filter) -> Query: ...
    def eval(self) -> PathSet: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[path]: ...


def ext(suffix: str) -> Filter:
    """Filter: pathlib's final suffix equals `suffix` ('.yaml'; case-sensitive)."""

def name(glob: str) -> Filter:
    """Filter: the final component matches the glob (`*` and `?`)."""

def absolute() -> Filter:
    """Filter: pathlib's is_absolute()."""

def match_pattern(pattern: str, string: str) -> bool:
    """Whether `string` matches the glob `pattern` (`*` and `?`)."""


class PathStore:
    """A table of paths: every distinct component once, every path a row. path(text, store=s)
    interns into s's table and every path derived from that one stays there — a store is how a
    program scopes a lifetime: pass one, keep it, drop it. Rows are never freed within a table;
    the table is freed with its last handle."""
    def __init__(self) -> None: ...
    def reserve(self, n: int) -> None: ...
    def stats(self) -> dict[str, int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


def default_store() -> PathStore:
    """The module's default PathStore: what path(text) without store= interns into."""


# --- generated: engines (regenerate with `pygim stubs`) ---
# Selection accepts FORMAT names, LIBRARY labels and aliases; .engine reports the label.
Engine = Literal[
    "json", "simdjson",
    "jsonl", "simdjson-ndjson", "ndjson",
    "toml", "toml++", "tomlplusplus",
    "yaml", "rapidyaml", "yml",
]

class jsonpath(path):
    """JSON via simdjson (strict, SIMD-accelerated); writes real JSON and rejects non-finite floats. Constructing one pins the engine (simdjson)."""
    def __init__(self, path: str | bytes | os.PathLike[str], *, store: PathStore | None = None) -> None: ...

class jsonlpath(path):
    """JSON Lines (ndjson) via simdjson's document stream: reads as a list, one item per document, and writes one compact document per line from a list root. Constructing one pins the engine (simdjson-ndjson)."""
    def __init__(self, path: str | bytes | os.PathLike[str], *, store: PathStore | None = None) -> None: ...

class tomlpath(path):
    """TOML via toml++: documents are tables (mapping root), there is no null, and dates and times are datetime objects (tomllib parity). Constructing one pins the engine (toml++)."""
    def __init__(self, path: str | bytes | os.PathLike[str], *, store: PathStore | None = None) -> None: ...

class yamlpath(path):
    """YAML 1.2 (core schema) via rapidyaml: anchors, aliases and merge keys are resolved; strings that would read back typed are quoted on write. Constructing one pins the engine (rapidyaml)."""
    def __init__(self, path: str | bytes | os.PathLike[str], *, store: PathStore | None = None) -> None: ...

ENGINES: tuple[EngineInfo, ...]
# --- end generated ---
