"""Type stubs for pygim.pathlike.

The compiled extension is untyped at runtime; this stub documents the stable
public contract of ``pygim.path(...)`` / ``pathlike.file``.
"""

import os
from typing import Any, Literal

Engine = Literal["yaml", "yml", "json", "toml"]

def path(path: str | os.PathLike[str], engine: Engine | None = None) -> file:
    """Wrap a path in a self-reading, self-decoding file().

    ``engine=`` pins the decoder for this object (inherited by derived paths);
    the default resolves from the file extension at read/write time.
    """

class file(os.PathLike[str]):
    def __init__(self, path: str | os.PathLike[str], engine: Engine | None = None) -> None: ...

    # -- decoding / encoding ------------------------------------------------
    def read(self, engine: Engine | None = None, key_cache: int = 256) -> Any:
        """Decode the file to native Python objects (GIL released during I/O
        and parsing). ``key_cache`` bounds key interning: 0 off, -1 unbounded."""

    def write(self, obj: Any, engine: Engine | None = None) -> None:
        """Serialise obj with the resolved engine. YAML/JSON accept
        dict/list/str/int/float/bool/None roots; TOML requires a mapping
        root, has no null, and additionally supports datetime values."""

    def read_bytes(self) -> bytes: ...

    # -- engine -------------------------------------------------------------
    @property
    def engine(self) -> str | None: ...

    # -- os.PathLike / identity ----------------------------------------------
    def __fspath__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

    # -- name components (pathlib parity) -------------------------------------
    @property
    def uri(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def stem(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def suffixes(self) -> list[str]: ...
    @property
    def parts(self) -> list[str]: ...

    # -- composition ----------------------------------------------------------
    def __truediv__(self, other: str | os.PathLike[str]) -> file: ...
    def __rtruediv__(self, other: str | os.PathLike[str]) -> file: ...
    def joinpath(self, *parts: str | os.PathLike[str]) -> file: ...
    @property
    def parent(self) -> file: ...
    @property
    def parents(self) -> list[file]: ...
    def with_suffix(self, suffix: str) -> file: ...
    def with_name(self, name: str) -> file: ...
    def with_stem(self, stem: str) -> file: ...
    def absolute(self) -> file: ...
    def resolve(self) -> file: ...

    # -- filesystem status ------------------------------------------------------
    def is_absolute(self) -> bool: ...
    def exists(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def is_symlink(self) -> bool: ...
    def size(self) -> int: ...

    # -- directory traversal (results inherit the engine pin) --------------------
    def iterdir(self) -> list[file]: ...
    def glob(self, pattern: str) -> list[file]: ...
    def rglob(self, pattern: str) -> list[file]: ...
    def pathset(self, pattern: str = "*") -> Any:
        """The glob results as a pygim.pathset.PathSet."""
