#!/usr/bin/env python
"""Generate src/_pygim_fast/pathlike/markdown/tables.h from this interpreter.

CommonMark leans on three Unicode facts and one HTML fact, and each one is a
table this script writes as constexpr data:

- punctuation: code points in the Unicode P or S general categories (the
  flanking rules of emphasis, CommonMark 0.31.2 §6.2);
- whitespace: the Zs category plus tab, line feed, form feed and carriage
  return (the same rules);
- case folding: the full Unicode case fold, which matches link labels
  (``[ẞ]`` matches a definition of ``[SS]``);
- entities: the HTML5 named character references that end in ``;`` (an
  entity reference is only recognised with its semicolon);
- ASCII folding: what Python-Markdown's heading ids keep of a character
  (NFKD, then only its ASCII part: ``é`` -> ``e``, ``ﬁ`` -> ``fi``), for the
  ``toc_slug`` policy.

The interpreter is the oracle: ``unicodedata`` for the categories,
``str.casefold`` for folding, ``html.entities.html5`` for entities and
``unicodedata.normalize("NFKD")`` for ASCII folding.
tests/unittests/test_pathlike_markdown.py asserts that the committed file
matches, when it runs under the Unicode version the file records.

Run:  python tests/static/gen_markdown_tables.py
"""

from __future__ import annotations

import html.entities
import sys
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "src" / "_pygim_fast" / "pathlike" / "markdown" / "tables.h"


def cpp_bytes(s: str) -> str:
    """A C++ string literal of the UTF-8 bytes of s, every non-ASCII-printable byte as an octal escape."""
    out = []
    for b in s.encode("utf-8"):
        c = chr(b)
        if c in '"\\' or not (0x20 <= b < 0x7F):
            out.append(f"\\{b:03o}")
        else:
            out.append(c)
    return '"' + "".join(out) + '"'


def ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in range(sys.maxunicode + 1):
        if pred(cp):
            if out and out[-1][1] == cp - 1:
                out[-1] = (out[-1][0], cp)
            else:
                out.append((cp, cp))
    return out


def render() -> str:
    punct = ranges(lambda cp: unicodedata.category(chr(cp))[0] in "PS")
    space = [cp for cp in range(sys.maxunicode + 1) if unicodedata.category(chr(cp)) == "Zs"]
    space = sorted(set(space) | {0x09, 0x0A, 0x0C, 0x0D})
    folds = [(cp, chr(cp).casefold()) for cp in range(sys.maxunicode + 1)
             if not 0xD800 <= cp <= 0xDFFF and chr(cp).casefold() != chr(cp)]
    entities = sorted((name[:-1], text) for name, text in html.entities.html5.items() if name.endswith(";"))
    ascii_folds = []
    for cp in range(0x80, sys.maxunicode + 1):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        folded = unicodedata.normalize("NFKD", chr(cp)).encode("ascii", "ignore").decode("ascii")
        if folded:
            ascii_folds.append((cp, folded))

    lines = [
        "#pragma once",
        "// pathlike/markdown/tables.h — GENERATED by tests/static/gen_markdown_tables.py; do not edit.",
        "//",
        f"// Unicode {unicodedata.unidata_version} (Python's unicodedata) and the HTML5 named character",
        "// references (html.entities.html5). Every table is sorted, so a lookup is a binary search",
        "// (unicode.h). Regenerate after a Python upgrade that changes the Unicode version.",
        "",
        "#include <string_view>",
        "",
        "namespace pygim::pathlike::markdown::tables {",
        "",
        f'inline constexpr std::string_view unicode_version = "{unicodedata.unidata_version}";',
        "",
        "struct cp_range {",
        "    char32_t lo;",
        "    char32_t hi;",
        "};",
        "struct fold {",
        "    char32_t cp;",
        "    std::string_view to;",
        "};",
        "struct entity {",
        "    std::string_view name;",
        "    std::string_view text;",
        "};",
        "struct ascii_fold {",
        "    char32_t cp;",
        "    std::string_view to;",
        "};",
        "",
        f"// Unicode P and S general categories: {len(punct)} ranges.",
        "inline constexpr cp_range punctuation[] = {",
    ]
    for i in range(0, len(punct), 4):
        lines.append("    " + " ".join(f"{{0x{lo:X}, 0x{hi:X}}}," for lo, hi in punct[i:i + 4]))
    lines += ["};", "", f"// Zs plus tab, line feed, form feed, carriage return: {len(space)} code points.",
              "inline constexpr char32_t whitespace[] = {"]
    for i in range(0, len(space), 8):
        lines.append("    " + " ".join(f"0x{cp:X}," for cp in space[i:i + 8]))
    lines += ["};", "", f"// Full case folding (str.casefold): {len(folds)} code points that fold.",
              "inline constexpr fold casefold[] = {"]
    for i in range(0, len(folds), 4):
        lines.append("    " + " ".join(f"{{0x{cp:X}, {cpp_bytes(to)}}}," for cp, to in folds[i:i + 4]))
    lines += ["};", "", f"// HTML5 named character references ending in ';' (name without '&' and ';'): {len(entities)}.",
              "inline constexpr entity entities[] = {"]
    for name, text in entities:
        lines.append(f"    {{{cpp_bytes(name)}, {cpp_bytes(text)}}},")
    lines += ["};", "", f"// NFKD's ASCII part of non-ASCII code points that have one: {len(ascii_folds)}.",
              "inline constexpr ascii_fold ascii_folds[] = {"]
    for i in range(0, len(ascii_folds), 4):
        lines.append("    " + " ".join(f"{{0x{cp:X}, {cpp_bytes(to)}}}," for cp, to in ascii_folds[i:i + 4]))
    lines += ["};", "", "}  // namespace pygim::pathlike::markdown::tables", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
