#!/usr/bin/env python
"""Generate tests/static/pathlike_parity_proofs.cpp from pathlib.

pathlib is the oracle for path semantics. This script asks PurePosixPath and
PureWindowsPath what each corpus string means — name, stem, suffix, suffixes,
parts, parent, str(), is_absolute — and emits one static_assert per fact
against basic_file<posix_strategy> / basic_file<windows_strategy>. The result is
compiled into every build (ext.pathlike.toml), so both strategies are proven on
every host, at compile time. tests/unittests/test_pathlike.py asserts the
committed file is current.

Run:  python tests/static/gen_pathlike_parity_proofs.py
"""

from __future__ import annotations

import sys
from pathlib import Path, PurePosixPath, PureWindowsPath

HERE = Path(__file__).resolve().parent
OUT = HERE / "pathlike_parity_proofs.cpp"

# Strings whose pathlib semantics are stable across supported Python versions
# ("a." and "..a" are excluded on purpose: their stem/suffix changed in 3.14).
COMMON = [
    "a.yaml", "a..b", ".bashrc", ".bashrc.swp", "..", ".", "", "a/b/", "/",
    "a//b", "archive.tar.gz", "a.b.c.d", "no_ext", "/abs/x.yml", "./rel",
    "spa ce/f.yaml", "...", "a...gz", "a/./b", "x.YAML", "a/b/c.yaml",
    "/a/b/c", "///triple", "a/../b", "dir/", "/x/y/",
]
POSIX_ONLY = ["//net/share/x", "//", "C:/not/a/drive"]
WINDOWS_ONLY = [
    r"C:\x\y.yaml", "C:/x/y.yaml", r"c:\X", "C:", "C:x", r"C:\\", r"\x\y", r"\\srv\share\x.toml",
    r"\\srv\share", "//srv/share/x", r"D:\a\b\..\c", r"C:\a b\c.json", "C://x",
]


def cpp_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cpp_list(items) -> str:
    return "{" + ", ".join(cpp_str(x) for x in items) + "}"


def facts(kind: str, cls, s: str) -> list[str]:
    p = cls(s)
    lit = cpp_str(s)
    return [
        f"static_assert({kind}::str_is({lit}, {cpp_str(str(p))}));",
        f"static_assert({kind}::name_is({lit}, {cpp_str(p.name)}));",
        f"static_assert({kind}::stem_is({lit}, {cpp_str(p.stem)}));",
        f"static_assert({kind}::suffix_is({lit}, {cpp_str(p.suffix)}));",
        f"static_assert({kind}::suffixes_are({lit}, {cpp_list(p.suffixes)}));",
        f"static_assert({kind}::parts_are({lit}, {cpp_list(p.parts)}));",
        f"static_assert({kind}::parent_is({lit}, {cpp_str(str(p.parent))}));",
        f"static_assert({kind}::is_absolute({lit}) == {'true' if p.is_absolute() else 'false'});",
    ]


def render() -> str:
    lines = [
        "// GENERATED by tests/static/gen_pathlike_parity_proofs.py — do not edit.",
        "//",
        "// pathlib is the oracle for path semantics: every assertion below is a fact",
        "// PurePosixPath / PureWindowsPath reported for the corpus, replayed against",
        "// basic_file<posix_strategy> / basic_file<windows_strategy> at compile time.",
        "// Compiled into every build (ext.pathlike.toml): a parity regression in either",
        "// strategy, on any host, produces no binary. Contributes no runtime code.",
        "",
        '#include "../../src/_pygim_fast/pathlike/core.h"',
        "",
        "#include <initializer_list>",
        "#include <string>",
        "#include <string_view>",
        "#include <vector>",
        "",
        "namespace {",
        "",
        "using namespace pygim::pathlike;",
        "",
        "// Every probe constructs a LOCAL object and returns a bool computed inside:",
        "// the libstdc++ of GCC 13/14 cannot constant-evaluate a short std::string",
        "// that escapes into the assertion expression, nor compare vectors of",
        "// temporaries there. (GCC 15+, libc++ and MSVC have no such limits.)",
        "template <class Strategy>",
        "struct probe {",
        "    using B = basic_file<Strategy>;",
        "    static consteval bool str_is(std::string_view s, std::string_view want) { B f(s); return f.fspath() == want; }",
        "    static consteval bool name_is(std::string_view s, std::string_view want) { B f(s); return f.name() == want; }",
        "    static consteval bool stem_is(std::string_view s, std::string_view want) { B f(s); return f.stem() == want; }",
        "    static consteval bool suffix_is(std::string_view s, std::string_view want) { B f(s); return f.suffix() == want; }",
        "    static consteval bool parent_is(std::string_view s, std::string_view want) { B f(s); B p = f.parent(); return p.fspath() == want; }",
        "    static consteval bool is_absolute(std::string_view s) { B f(s); return f.is_absolute(); }",
        "    static consteval bool same(const std::vector<std::string>& got, std::initializer_list<std::string_view> want) {",
        "        if (got.size() != want.size()) return false;",
        "        std::size_t i = 0;",
        "        for (std::string_view w : want) { if (got[i++] != w) return false; }",
        "        return true;",
        "    }",
        "    static consteval bool suffixes_are(std::string_view s, std::initializer_list<std::string_view> want) {",
        "        B f(s); const std::vector<std::string> got = f.suffixes(); return same(got, want);",
        "    }",
        "    static consteval bool parts_are(std::string_view s, std::initializer_list<std::string_view> want) {",
        "        B f(s); const std::vector<std::string> got = f.parts(); return same(got, want);",
        "    }",
        "};",
        "using px = probe<posix_strategy>;",
        "using wx = probe<windows_strategy>;",
        "",
        "// ── PurePosixPath ──────────────────────────────────────────────────────────",
    ]
    for s in COMMON + POSIX_ONLY:
        lines += [f"// {s!r}", *facts("px", PurePosixPath, s)]
    lines += ["", "// ── PureWindowsPath ────────────────────────────────────────────────────────"]
    for s in COMMON + WINDOWS_ONLY:
        lines += [f"// {s!r}", *facts("wx", PureWindowsPath, s)]
    lines += ["", "[[maybe_unused]] constexpr bool kParityProofsCompiled = true;", "", "}  // namespace", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is stale: run {Path(__file__).name}")
            return 1
        print(f"{OUT}: up to date")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({text.count('static_assert')} assertions)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
