// GENERATED by tests/static/gen_pathlike_parity_proofs.py — do not edit.
//
// pathlib is the oracle for path semantics: every assertion below is a fact
// PurePosixPath / PureWindowsPath reported for the corpus, replayed against
// basic_file<posix_strategy> / basic_file<windows_strategy> at compile time.
// Compiled into every build (ext.pathlike.toml): a parity regression in either
// strategy, on any host, produces no binary. Contributes no runtime code.

#include "../../src/_pygim_fast/pathlike/core.h"

#include <initializer_list>
#include <string>
#include <string_view>
#include <vector>

namespace {

using namespace pygim::pathlike;

// Every probe constructs a LOCAL object and returns a bool computed inside:
// the libstdc++ of GCC 13/14 cannot constant-evaluate a short std::string
// that escapes into the assertion expression, nor compare vectors of
// temporaries there. (GCC 15+, libc++ and MSVC have no such limits.)
template <class Strategy>
struct probe {
    using B = basic_file<Strategy>;
    static consteval bool str_is(std::string_view s, std::string_view want) { B f(s); return f.fspath() == want; }
    static consteval bool name_is(std::string_view s, std::string_view want) { B f(s); return f.name() == want; }
    static consteval bool stem_is(std::string_view s, std::string_view want) { B f(s); return f.stem() == want; }
    static consteval bool suffix_is(std::string_view s, std::string_view want) { B f(s); return f.suffix() == want; }
    static consteval bool parent_is(std::string_view s, std::string_view want) { B f(s); B p = f.parent(); return p.fspath() == want; }
    static consteval bool is_absolute(std::string_view s) { B f(s); return f.is_absolute(); }
    static consteval bool joined_is(std::string_view a, std::string_view b, std::string_view want) { B f(a); B j = f.joined(b); return j.fspath() == want; }
    static consteval bool rjoined_is(std::string_view a, std::string_view b, std::string_view want) { B f(a); B j = f.rjoined(b); return j.fspath() == want; }
    static consteval bool with_name_is(std::string_view s, std::string_view n, std::string_view want) { B f(s); B r = f.with_name(n); return r.fspath() == want; }
    static consteval bool with_suffix_is(std::string_view s, std::string_view x, std::string_view want) { B f(s); B r = f.with_suffix(x); return r.fspath() == want; }
    static consteval bool with_stem_is(std::string_view s, std::string_view x, std::string_view want) { B f(s); B r = f.with_stem(x); return r.fspath() == want; }
    static consteval bool same(const std::vector<std::string>& got, std::initializer_list<std::string_view> want) {
        if (got.size() != want.size()) return false;
        std::size_t i = 0;
        for (std::string_view w : want) { if (got[i++] != w) return false; }
        return true;
    }
    static consteval bool suffixes_are(std::string_view s, std::initializer_list<std::string_view> want) {
        B f(s); const std::vector<std::string> got = f.suffixes(); return same(got, want);
    }
    static consteval bool parts_are(std::string_view s, std::initializer_list<std::string_view> want) {
        B f(s); const std::vector<std::string> got = f.parts(); return same(got, want);
    }
};
using px = probe<posix_strategy>;
using wx = probe<windows_strategy>;

// ── PurePosixPath ──────────────────────────────────────────────────────────
// 'a.yaml'
static_assert(px::str_is("a.yaml", "a.yaml"));
static_assert(px::name_is("a.yaml", "a.yaml"));
static_assert(px::stem_is("a.yaml", "a"));
static_assert(px::suffix_is("a.yaml", ".yaml"));
static_assert(px::suffixes_are("a.yaml", {".yaml"}));
static_assert(px::parts_are("a.yaml", {"a.yaml"}));
static_assert(px::parent_is("a.yaml", "."));
static_assert(px::is_absolute("a.yaml") == false);
// 'a..b'
static_assert(px::str_is("a..b", "a..b"));
static_assert(px::name_is("a..b", "a..b"));
static_assert(px::stem_is("a..b", "a."));
static_assert(px::suffix_is("a..b", ".b"));
static_assert(px::suffixes_are("a..b", {".", ".b"}));
static_assert(px::parts_are("a..b", {"a..b"}));
static_assert(px::parent_is("a..b", "."));
static_assert(px::is_absolute("a..b") == false);
// '.bashrc'
static_assert(px::str_is(".bashrc", ".bashrc"));
static_assert(px::name_is(".bashrc", ".bashrc"));
static_assert(px::stem_is(".bashrc", ".bashrc"));
static_assert(px::suffix_is(".bashrc", ""));
static_assert(px::suffixes_are(".bashrc", {}));
static_assert(px::parts_are(".bashrc", {".bashrc"}));
static_assert(px::parent_is(".bashrc", "."));
static_assert(px::is_absolute(".bashrc") == false);
// '.bashrc.swp'
static_assert(px::str_is(".bashrc.swp", ".bashrc.swp"));
static_assert(px::name_is(".bashrc.swp", ".bashrc.swp"));
static_assert(px::stem_is(".bashrc.swp", ".bashrc"));
static_assert(px::suffix_is(".bashrc.swp", ".swp"));
static_assert(px::suffixes_are(".bashrc.swp", {".swp"}));
static_assert(px::parts_are(".bashrc.swp", {".bashrc.swp"}));
static_assert(px::parent_is(".bashrc.swp", "."));
static_assert(px::is_absolute(".bashrc.swp") == false);
// '..'
static_assert(px::str_is("..", ".."));
static_assert(px::name_is("..", ".."));
static_assert(px::stem_is("..", ".."));
static_assert(px::suffix_is("..", ""));
static_assert(px::suffixes_are("..", {}));
static_assert(px::parts_are("..", {".."}));
static_assert(px::parent_is("..", "."));
static_assert(px::is_absolute("..") == false);
// '.'
static_assert(px::str_is(".", "."));
static_assert(px::name_is(".", ""));
static_assert(px::stem_is(".", ""));
static_assert(px::suffix_is(".", ""));
static_assert(px::suffixes_are(".", {}));
static_assert(px::parts_are(".", {}));
static_assert(px::parent_is(".", "."));
static_assert(px::is_absolute(".") == false);
// ''
static_assert(px::str_is("", "."));
static_assert(px::name_is("", ""));
static_assert(px::stem_is("", ""));
static_assert(px::suffix_is("", ""));
static_assert(px::suffixes_are("", {}));
static_assert(px::parts_are("", {}));
static_assert(px::parent_is("", "."));
static_assert(px::is_absolute("") == false);
// 'a/b/'
static_assert(px::str_is("a/b/", "a/b"));
static_assert(px::name_is("a/b/", "b"));
static_assert(px::stem_is("a/b/", "b"));
static_assert(px::suffix_is("a/b/", ""));
static_assert(px::suffixes_are("a/b/", {}));
static_assert(px::parts_are("a/b/", {"a", "b"}));
static_assert(px::parent_is("a/b/", "a"));
static_assert(px::is_absolute("a/b/") == false);
// '/'
static_assert(px::str_is("/", "/"));
static_assert(px::name_is("/", ""));
static_assert(px::stem_is("/", ""));
static_assert(px::suffix_is("/", ""));
static_assert(px::suffixes_are("/", {}));
static_assert(px::parts_are("/", {"/"}));
static_assert(px::parent_is("/", "/"));
static_assert(px::is_absolute("/") == true);
// 'a//b'
static_assert(px::str_is("a//b", "a/b"));
static_assert(px::name_is("a//b", "b"));
static_assert(px::stem_is("a//b", "b"));
static_assert(px::suffix_is("a//b", ""));
static_assert(px::suffixes_are("a//b", {}));
static_assert(px::parts_are("a//b", {"a", "b"}));
static_assert(px::parent_is("a//b", "a"));
static_assert(px::is_absolute("a//b") == false);
// 'archive.tar.gz'
static_assert(px::str_is("archive.tar.gz", "archive.tar.gz"));
static_assert(px::name_is("archive.tar.gz", "archive.tar.gz"));
static_assert(px::stem_is("archive.tar.gz", "archive.tar"));
static_assert(px::suffix_is("archive.tar.gz", ".gz"));
static_assert(px::suffixes_are("archive.tar.gz", {".tar", ".gz"}));
static_assert(px::parts_are("archive.tar.gz", {"archive.tar.gz"}));
static_assert(px::parent_is("archive.tar.gz", "."));
static_assert(px::is_absolute("archive.tar.gz") == false);
// 'a.b.c.d'
static_assert(px::str_is("a.b.c.d", "a.b.c.d"));
static_assert(px::name_is("a.b.c.d", "a.b.c.d"));
static_assert(px::stem_is("a.b.c.d", "a.b.c"));
static_assert(px::suffix_is("a.b.c.d", ".d"));
static_assert(px::suffixes_are("a.b.c.d", {".b", ".c", ".d"}));
static_assert(px::parts_are("a.b.c.d", {"a.b.c.d"}));
static_assert(px::parent_is("a.b.c.d", "."));
static_assert(px::is_absolute("a.b.c.d") == false);
// 'no_ext'
static_assert(px::str_is("no_ext", "no_ext"));
static_assert(px::name_is("no_ext", "no_ext"));
static_assert(px::stem_is("no_ext", "no_ext"));
static_assert(px::suffix_is("no_ext", ""));
static_assert(px::suffixes_are("no_ext", {}));
static_assert(px::parts_are("no_ext", {"no_ext"}));
static_assert(px::parent_is("no_ext", "."));
static_assert(px::is_absolute("no_ext") == false);
// '/abs/x.yml'
static_assert(px::str_is("/abs/x.yml", "/abs/x.yml"));
static_assert(px::name_is("/abs/x.yml", "x.yml"));
static_assert(px::stem_is("/abs/x.yml", "x"));
static_assert(px::suffix_is("/abs/x.yml", ".yml"));
static_assert(px::suffixes_are("/abs/x.yml", {".yml"}));
static_assert(px::parts_are("/abs/x.yml", {"/", "abs", "x.yml"}));
static_assert(px::parent_is("/abs/x.yml", "/abs"));
static_assert(px::is_absolute("/abs/x.yml") == true);
// './rel'
static_assert(px::str_is("./rel", "rel"));
static_assert(px::name_is("./rel", "rel"));
static_assert(px::stem_is("./rel", "rel"));
static_assert(px::suffix_is("./rel", ""));
static_assert(px::suffixes_are("./rel", {}));
static_assert(px::parts_are("./rel", {"rel"}));
static_assert(px::parent_is("./rel", "."));
static_assert(px::is_absolute("./rel") == false);
// 'spa ce/f.yaml'
static_assert(px::str_is("spa ce/f.yaml", "spa ce/f.yaml"));
static_assert(px::name_is("spa ce/f.yaml", "f.yaml"));
static_assert(px::stem_is("spa ce/f.yaml", "f"));
static_assert(px::suffix_is("spa ce/f.yaml", ".yaml"));
static_assert(px::suffixes_are("spa ce/f.yaml", {".yaml"}));
static_assert(px::parts_are("spa ce/f.yaml", {"spa ce", "f.yaml"}));
static_assert(px::parent_is("spa ce/f.yaml", "spa ce"));
static_assert(px::is_absolute("spa ce/f.yaml") == false);
// '...'
static_assert(px::str_is("...", "..."));
static_assert(px::name_is("...", "..."));
static_assert(px::stem_is("...", "..."));
static_assert(px::suffix_is("...", ""));
static_assert(px::suffixes_are("...", {}));
static_assert(px::parts_are("...", {"..."}));
static_assert(px::parent_is("...", "."));
static_assert(px::is_absolute("...") == false);
// 'a...gz'
static_assert(px::str_is("a...gz", "a...gz"));
static_assert(px::name_is("a...gz", "a...gz"));
static_assert(px::stem_is("a...gz", "a.."));
static_assert(px::suffix_is("a...gz", ".gz"));
static_assert(px::suffixes_are("a...gz", {".", ".", ".gz"}));
static_assert(px::parts_are("a...gz", {"a...gz"}));
static_assert(px::parent_is("a...gz", "."));
static_assert(px::is_absolute("a...gz") == false);
// 'a/./b'
static_assert(px::str_is("a/./b", "a/b"));
static_assert(px::name_is("a/./b", "b"));
static_assert(px::stem_is("a/./b", "b"));
static_assert(px::suffix_is("a/./b", ""));
static_assert(px::suffixes_are("a/./b", {}));
static_assert(px::parts_are("a/./b", {"a", "b"}));
static_assert(px::parent_is("a/./b", "a"));
static_assert(px::is_absolute("a/./b") == false);
// 'x.YAML'
static_assert(px::str_is("x.YAML", "x.YAML"));
static_assert(px::name_is("x.YAML", "x.YAML"));
static_assert(px::stem_is("x.YAML", "x"));
static_assert(px::suffix_is("x.YAML", ".YAML"));
static_assert(px::suffixes_are("x.YAML", {".YAML"}));
static_assert(px::parts_are("x.YAML", {"x.YAML"}));
static_assert(px::parent_is("x.YAML", "."));
static_assert(px::is_absolute("x.YAML") == false);
// 'a/b/c.yaml'
static_assert(px::str_is("a/b/c.yaml", "a/b/c.yaml"));
static_assert(px::name_is("a/b/c.yaml", "c.yaml"));
static_assert(px::stem_is("a/b/c.yaml", "c"));
static_assert(px::suffix_is("a/b/c.yaml", ".yaml"));
static_assert(px::suffixes_are("a/b/c.yaml", {".yaml"}));
static_assert(px::parts_are("a/b/c.yaml", {"a", "b", "c.yaml"}));
static_assert(px::parent_is("a/b/c.yaml", "a/b"));
static_assert(px::is_absolute("a/b/c.yaml") == false);
// '/a/b/c'
static_assert(px::str_is("/a/b/c", "/a/b/c"));
static_assert(px::name_is("/a/b/c", "c"));
static_assert(px::stem_is("/a/b/c", "c"));
static_assert(px::suffix_is("/a/b/c", ""));
static_assert(px::suffixes_are("/a/b/c", {}));
static_assert(px::parts_are("/a/b/c", {"/", "a", "b", "c"}));
static_assert(px::parent_is("/a/b/c", "/a/b"));
static_assert(px::is_absolute("/a/b/c") == true);
// 'a/../b'
static_assert(px::str_is("a/../b", "a/../b"));
static_assert(px::name_is("a/../b", "b"));
static_assert(px::stem_is("a/../b", "b"));
static_assert(px::suffix_is("a/../b", ""));
static_assert(px::suffixes_are("a/../b", {}));
static_assert(px::parts_are("a/../b", {"a", "..", "b"}));
static_assert(px::parent_is("a/../b", "a/.."));
static_assert(px::is_absolute("a/../b") == false);
// 'dir/'
static_assert(px::str_is("dir/", "dir"));
static_assert(px::name_is("dir/", "dir"));
static_assert(px::stem_is("dir/", "dir"));
static_assert(px::suffix_is("dir/", ""));
static_assert(px::suffixes_are("dir/", {}));
static_assert(px::parts_are("dir/", {"dir"}));
static_assert(px::parent_is("dir/", "."));
static_assert(px::is_absolute("dir/") == false);
// '/x/y/'
static_assert(px::str_is("/x/y/", "/x/y"));
static_assert(px::name_is("/x/y/", "y"));
static_assert(px::stem_is("/x/y/", "y"));
static_assert(px::suffix_is("/x/y/", ""));
static_assert(px::suffixes_are("/x/y/", {}));
static_assert(px::parts_are("/x/y/", {"/", "x", "y"}));
static_assert(px::parent_is("/x/y/", "/x"));
static_assert(px::is_absolute("/x/y/") == true);
// '//net/share/x'
static_assert(px::str_is("//net/share/x", "//net/share/x"));
static_assert(px::name_is("//net/share/x", "x"));
static_assert(px::stem_is("//net/share/x", "x"));
static_assert(px::suffix_is("//net/share/x", ""));
static_assert(px::suffixes_are("//net/share/x", {}));
static_assert(px::parts_are("//net/share/x", {"//", "net", "share", "x"}));
static_assert(px::parent_is("//net/share/x", "//net/share"));
static_assert(px::is_absolute("//net/share/x") == true);
// '//'
static_assert(px::str_is("//", "//"));
static_assert(px::name_is("//", ""));
static_assert(px::stem_is("//", ""));
static_assert(px::suffix_is("//", ""));
static_assert(px::suffixes_are("//", {}));
static_assert(px::parts_are("//", {"//"}));
static_assert(px::parent_is("//", "//"));
static_assert(px::is_absolute("//") == true);
// 'C:/not/a/drive'
static_assert(px::str_is("C:/not/a/drive", "C:/not/a/drive"));
static_assert(px::name_is("C:/not/a/drive", "drive"));
static_assert(px::stem_is("C:/not/a/drive", "drive"));
static_assert(px::suffix_is("C:/not/a/drive", ""));
static_assert(px::suffixes_are("C:/not/a/drive", {}));
static_assert(px::parts_are("C:/not/a/drive", {"C:", "not", "a", "drive"}));
static_assert(px::parent_is("C:/not/a/drive", "C:/not/a"));
static_assert(px::is_absolute("C:/not/a/drive") == false);
// '///triple'
static_assert(px::str_is("///triple", "/triple"));
static_assert(px::name_is("///triple", "triple"));
static_assert(px::stem_is("///triple", "triple"));
static_assert(px::suffix_is("///triple", ""));
static_assert(px::suffixes_are("///triple", {}));
static_assert(px::parts_are("///triple", {"/", "triple"}));
static_assert(px::parent_is("///triple", "/"));
static_assert(px::is_absolute("///triple") == true);
// joining
static_assert(px::joined_is("a/b", "c", "a/b/c"));
static_assert(px::rjoined_is("a/b", "c", "c/a/b"));
static_assert(px::joined_is("a/b", "/x", "/x"));
static_assert(px::rjoined_is("a/b", "/x", "/x/a/b"));
static_assert(px::joined_is("/a/b", "c/d", "/a/b/c/d"));
static_assert(px::rjoined_is("/a/b", "c/d", "/a/b"));
static_assert(px::joined_is("", "x", "x"));
static_assert(px::rjoined_is("", "x", "x"));
static_assert(px::joined_is("a", "b/c/", "a/b/c"));
static_assert(px::rjoined_is("a", "b/c/", "b/c/a"));
static_assert(px::joined_is("/", "x", "/x"));
static_assert(px::rjoined_is("/", "x", "/"));
static_assert(px::joined_is("a/b", "", "a/b"));
static_assert(px::rjoined_is("a/b", "", "a/b"));
static_assert(px::joined_is("a/b", ".", "a/b"));
static_assert(px::rjoined_is("a/b", ".", "a/b"));
static_assert(px::joined_is("a/b", "..", "a/b/.."));
static_assert(px::rjoined_is("a/b", "..", "../a/b"));
static_assert(px::joined_is("a//b", "c//d", "a/b/c/d"));
static_assert(px::rjoined_is("a//b", "c//d", "c/d/a/b"));
static_assert(px::joined_is("/a", "/", "/"));
static_assert(px::rjoined_is("/a", "/", "/a"));
static_assert(px::joined_is("x", "y/../z", "x/y/../z"));
static_assert(px::rjoined_is("x", "y/../z", "y/../z/x"));
static_assert(px::joined_is("spa ce", "f g", "spa ce/f g"));
static_assert(px::rjoined_is("spa ce", "f g", "f g/spa ce"));
// with_name / with_suffix / with_stem
static_assert(px::with_name_is("a/b.yaml", "z.txt", "a/z.txt"));
static_assert(px::with_name_is("a/b.yaml", "..", "a/.."));
static_assert(px::with_name_is("x", "y.z", "y.z"));
static_assert(px::with_suffix_is("a/b.yaml", ".json", "a/b.json"));
static_assert(px::with_suffix_is("a/b.tar.gz", ".bz2", "a/b.tar.bz2"));
static_assert(px::with_suffix_is("a/b.tar.gz", "", "a/b.tar"));
static_assert(px::with_suffix_is("no_ext", ".txt", "no_ext.txt"));
static_assert(px::with_stem_is("a/b.yaml", "q", "a/q.yaml"));
static_assert(px::with_stem_is("a/b.tar.gz", "q", "a/q.gz"));

// ── PureWindowsPath ────────────────────────────────────────────────────────
// 'a.yaml'
static_assert(wx::str_is("a.yaml", "a.yaml"));
static_assert(wx::name_is("a.yaml", "a.yaml"));
static_assert(wx::stem_is("a.yaml", "a"));
static_assert(wx::suffix_is("a.yaml", ".yaml"));
static_assert(wx::suffixes_are("a.yaml", {".yaml"}));
static_assert(wx::parts_are("a.yaml", {"a.yaml"}));
static_assert(wx::parent_is("a.yaml", "."));
static_assert(wx::is_absolute("a.yaml") == false);
// 'a..b'
static_assert(wx::str_is("a..b", "a..b"));
static_assert(wx::name_is("a..b", "a..b"));
static_assert(wx::stem_is("a..b", "a."));
static_assert(wx::suffix_is("a..b", ".b"));
static_assert(wx::suffixes_are("a..b", {".", ".b"}));
static_assert(wx::parts_are("a..b", {"a..b"}));
static_assert(wx::parent_is("a..b", "."));
static_assert(wx::is_absolute("a..b") == false);
// '.bashrc'
static_assert(wx::str_is(".bashrc", ".bashrc"));
static_assert(wx::name_is(".bashrc", ".bashrc"));
static_assert(wx::stem_is(".bashrc", ".bashrc"));
static_assert(wx::suffix_is(".bashrc", ""));
static_assert(wx::suffixes_are(".bashrc", {}));
static_assert(wx::parts_are(".bashrc", {".bashrc"}));
static_assert(wx::parent_is(".bashrc", "."));
static_assert(wx::is_absolute(".bashrc") == false);
// '.bashrc.swp'
static_assert(wx::str_is(".bashrc.swp", ".bashrc.swp"));
static_assert(wx::name_is(".bashrc.swp", ".bashrc.swp"));
static_assert(wx::stem_is(".bashrc.swp", ".bashrc"));
static_assert(wx::suffix_is(".bashrc.swp", ".swp"));
static_assert(wx::suffixes_are(".bashrc.swp", {".swp"}));
static_assert(wx::parts_are(".bashrc.swp", {".bashrc.swp"}));
static_assert(wx::parent_is(".bashrc.swp", "."));
static_assert(wx::is_absolute(".bashrc.swp") == false);
// '..'
static_assert(wx::str_is("..", ".."));
static_assert(wx::name_is("..", ".."));
static_assert(wx::stem_is("..", ".."));
static_assert(wx::suffix_is("..", ""));
static_assert(wx::suffixes_are("..", {}));
static_assert(wx::parts_are("..", {".."}));
static_assert(wx::parent_is("..", "."));
static_assert(wx::is_absolute("..") == false);
// '.'
static_assert(wx::str_is(".", "."));
static_assert(wx::name_is(".", ""));
static_assert(wx::stem_is(".", ""));
static_assert(wx::suffix_is(".", ""));
static_assert(wx::suffixes_are(".", {}));
static_assert(wx::parts_are(".", {}));
static_assert(wx::parent_is(".", "."));
static_assert(wx::is_absolute(".") == false);
// ''
static_assert(wx::str_is("", "."));
static_assert(wx::name_is("", ""));
static_assert(wx::stem_is("", ""));
static_assert(wx::suffix_is("", ""));
static_assert(wx::suffixes_are("", {}));
static_assert(wx::parts_are("", {}));
static_assert(wx::parent_is("", "."));
static_assert(wx::is_absolute("") == false);
// 'a/b/'
static_assert(wx::str_is("a/b/", "a\\b"));
static_assert(wx::name_is("a/b/", "b"));
static_assert(wx::stem_is("a/b/", "b"));
static_assert(wx::suffix_is("a/b/", ""));
static_assert(wx::suffixes_are("a/b/", {}));
static_assert(wx::parts_are("a/b/", {"a", "b"}));
static_assert(wx::parent_is("a/b/", "a"));
static_assert(wx::is_absolute("a/b/") == false);
// '/'
static_assert(wx::str_is("/", "\\"));
static_assert(wx::name_is("/", ""));
static_assert(wx::stem_is("/", ""));
static_assert(wx::suffix_is("/", ""));
static_assert(wx::suffixes_are("/", {}));
static_assert(wx::parts_are("/", {"\\"}));
static_assert(wx::parent_is("/", "\\"));
static_assert(wx::is_absolute("/") == false);
// 'a//b'
static_assert(wx::str_is("a//b", "a\\b"));
static_assert(wx::name_is("a//b", "b"));
static_assert(wx::stem_is("a//b", "b"));
static_assert(wx::suffix_is("a//b", ""));
static_assert(wx::suffixes_are("a//b", {}));
static_assert(wx::parts_are("a//b", {"a", "b"}));
static_assert(wx::parent_is("a//b", "a"));
static_assert(wx::is_absolute("a//b") == false);
// 'archive.tar.gz'
static_assert(wx::str_is("archive.tar.gz", "archive.tar.gz"));
static_assert(wx::name_is("archive.tar.gz", "archive.tar.gz"));
static_assert(wx::stem_is("archive.tar.gz", "archive.tar"));
static_assert(wx::suffix_is("archive.tar.gz", ".gz"));
static_assert(wx::suffixes_are("archive.tar.gz", {".tar", ".gz"}));
static_assert(wx::parts_are("archive.tar.gz", {"archive.tar.gz"}));
static_assert(wx::parent_is("archive.tar.gz", "."));
static_assert(wx::is_absolute("archive.tar.gz") == false);
// 'a.b.c.d'
static_assert(wx::str_is("a.b.c.d", "a.b.c.d"));
static_assert(wx::name_is("a.b.c.d", "a.b.c.d"));
static_assert(wx::stem_is("a.b.c.d", "a.b.c"));
static_assert(wx::suffix_is("a.b.c.d", ".d"));
static_assert(wx::suffixes_are("a.b.c.d", {".b", ".c", ".d"}));
static_assert(wx::parts_are("a.b.c.d", {"a.b.c.d"}));
static_assert(wx::parent_is("a.b.c.d", "."));
static_assert(wx::is_absolute("a.b.c.d") == false);
// 'no_ext'
static_assert(wx::str_is("no_ext", "no_ext"));
static_assert(wx::name_is("no_ext", "no_ext"));
static_assert(wx::stem_is("no_ext", "no_ext"));
static_assert(wx::suffix_is("no_ext", ""));
static_assert(wx::suffixes_are("no_ext", {}));
static_assert(wx::parts_are("no_ext", {"no_ext"}));
static_assert(wx::parent_is("no_ext", "."));
static_assert(wx::is_absolute("no_ext") == false);
// '/abs/x.yml'
static_assert(wx::str_is("/abs/x.yml", "\\abs\\x.yml"));
static_assert(wx::name_is("/abs/x.yml", "x.yml"));
static_assert(wx::stem_is("/abs/x.yml", "x"));
static_assert(wx::suffix_is("/abs/x.yml", ".yml"));
static_assert(wx::suffixes_are("/abs/x.yml", {".yml"}));
static_assert(wx::parts_are("/abs/x.yml", {"\\", "abs", "x.yml"}));
static_assert(wx::parent_is("/abs/x.yml", "\\abs"));
static_assert(wx::is_absolute("/abs/x.yml") == false);
// './rel'
static_assert(wx::str_is("./rel", "rel"));
static_assert(wx::name_is("./rel", "rel"));
static_assert(wx::stem_is("./rel", "rel"));
static_assert(wx::suffix_is("./rel", ""));
static_assert(wx::suffixes_are("./rel", {}));
static_assert(wx::parts_are("./rel", {"rel"}));
static_assert(wx::parent_is("./rel", "."));
static_assert(wx::is_absolute("./rel") == false);
// 'spa ce/f.yaml'
static_assert(wx::str_is("spa ce/f.yaml", "spa ce\\f.yaml"));
static_assert(wx::name_is("spa ce/f.yaml", "f.yaml"));
static_assert(wx::stem_is("spa ce/f.yaml", "f"));
static_assert(wx::suffix_is("spa ce/f.yaml", ".yaml"));
static_assert(wx::suffixes_are("spa ce/f.yaml", {".yaml"}));
static_assert(wx::parts_are("spa ce/f.yaml", {"spa ce", "f.yaml"}));
static_assert(wx::parent_is("spa ce/f.yaml", "spa ce"));
static_assert(wx::is_absolute("spa ce/f.yaml") == false);
// '...'
static_assert(wx::str_is("...", "..."));
static_assert(wx::name_is("...", "..."));
static_assert(wx::stem_is("...", "..."));
static_assert(wx::suffix_is("...", ""));
static_assert(wx::suffixes_are("...", {}));
static_assert(wx::parts_are("...", {"..."}));
static_assert(wx::parent_is("...", "."));
static_assert(wx::is_absolute("...") == false);
// 'a...gz'
static_assert(wx::str_is("a...gz", "a...gz"));
static_assert(wx::name_is("a...gz", "a...gz"));
static_assert(wx::stem_is("a...gz", "a.."));
static_assert(wx::suffix_is("a...gz", ".gz"));
static_assert(wx::suffixes_are("a...gz", {".", ".", ".gz"}));
static_assert(wx::parts_are("a...gz", {"a...gz"}));
static_assert(wx::parent_is("a...gz", "."));
static_assert(wx::is_absolute("a...gz") == false);
// 'a/./b'
static_assert(wx::str_is("a/./b", "a\\b"));
static_assert(wx::name_is("a/./b", "b"));
static_assert(wx::stem_is("a/./b", "b"));
static_assert(wx::suffix_is("a/./b", ""));
static_assert(wx::suffixes_are("a/./b", {}));
static_assert(wx::parts_are("a/./b", {"a", "b"}));
static_assert(wx::parent_is("a/./b", "a"));
static_assert(wx::is_absolute("a/./b") == false);
// 'x.YAML'
static_assert(wx::str_is("x.YAML", "x.YAML"));
static_assert(wx::name_is("x.YAML", "x.YAML"));
static_assert(wx::stem_is("x.YAML", "x"));
static_assert(wx::suffix_is("x.YAML", ".YAML"));
static_assert(wx::suffixes_are("x.YAML", {".YAML"}));
static_assert(wx::parts_are("x.YAML", {"x.YAML"}));
static_assert(wx::parent_is("x.YAML", "."));
static_assert(wx::is_absolute("x.YAML") == false);
// 'a/b/c.yaml'
static_assert(wx::str_is("a/b/c.yaml", "a\\b\\c.yaml"));
static_assert(wx::name_is("a/b/c.yaml", "c.yaml"));
static_assert(wx::stem_is("a/b/c.yaml", "c"));
static_assert(wx::suffix_is("a/b/c.yaml", ".yaml"));
static_assert(wx::suffixes_are("a/b/c.yaml", {".yaml"}));
static_assert(wx::parts_are("a/b/c.yaml", {"a", "b", "c.yaml"}));
static_assert(wx::parent_is("a/b/c.yaml", "a\\b"));
static_assert(wx::is_absolute("a/b/c.yaml") == false);
// '/a/b/c'
static_assert(wx::str_is("/a/b/c", "\\a\\b\\c"));
static_assert(wx::name_is("/a/b/c", "c"));
static_assert(wx::stem_is("/a/b/c", "c"));
static_assert(wx::suffix_is("/a/b/c", ""));
static_assert(wx::suffixes_are("/a/b/c", {}));
static_assert(wx::parts_are("/a/b/c", {"\\", "a", "b", "c"}));
static_assert(wx::parent_is("/a/b/c", "\\a\\b"));
static_assert(wx::is_absolute("/a/b/c") == false);
// 'a/../b'
static_assert(wx::str_is("a/../b", "a\\..\\b"));
static_assert(wx::name_is("a/../b", "b"));
static_assert(wx::stem_is("a/../b", "b"));
static_assert(wx::suffix_is("a/../b", ""));
static_assert(wx::suffixes_are("a/../b", {}));
static_assert(wx::parts_are("a/../b", {"a", "..", "b"}));
static_assert(wx::parent_is("a/../b", "a\\.."));
static_assert(wx::is_absolute("a/../b") == false);
// 'dir/'
static_assert(wx::str_is("dir/", "dir"));
static_assert(wx::name_is("dir/", "dir"));
static_assert(wx::stem_is("dir/", "dir"));
static_assert(wx::suffix_is("dir/", ""));
static_assert(wx::suffixes_are("dir/", {}));
static_assert(wx::parts_are("dir/", {"dir"}));
static_assert(wx::parent_is("dir/", "."));
static_assert(wx::is_absolute("dir/") == false);
// '/x/y/'
static_assert(wx::str_is("/x/y/", "\\x\\y"));
static_assert(wx::name_is("/x/y/", "y"));
static_assert(wx::stem_is("/x/y/", "y"));
static_assert(wx::suffix_is("/x/y/", ""));
static_assert(wx::suffixes_are("/x/y/", {}));
static_assert(wx::parts_are("/x/y/", {"\\", "x", "y"}));
static_assert(wx::parent_is("/x/y/", "\\x"));
static_assert(wx::is_absolute("/x/y/") == false);
// 'C:\\x\\y.yaml'
static_assert(wx::str_is("C:\\x\\y.yaml", "C:\\x\\y.yaml"));
static_assert(wx::name_is("C:\\x\\y.yaml", "y.yaml"));
static_assert(wx::stem_is("C:\\x\\y.yaml", "y"));
static_assert(wx::suffix_is("C:\\x\\y.yaml", ".yaml"));
static_assert(wx::suffixes_are("C:\\x\\y.yaml", {".yaml"}));
static_assert(wx::parts_are("C:\\x\\y.yaml", {"C:\\", "x", "y.yaml"}));
static_assert(wx::parent_is("C:\\x\\y.yaml", "C:\\x"));
static_assert(wx::is_absolute("C:\\x\\y.yaml") == true);
// 'C:/x/y.yaml'
static_assert(wx::str_is("C:/x/y.yaml", "C:\\x\\y.yaml"));
static_assert(wx::name_is("C:/x/y.yaml", "y.yaml"));
static_assert(wx::stem_is("C:/x/y.yaml", "y"));
static_assert(wx::suffix_is("C:/x/y.yaml", ".yaml"));
static_assert(wx::suffixes_are("C:/x/y.yaml", {".yaml"}));
static_assert(wx::parts_are("C:/x/y.yaml", {"C:\\", "x", "y.yaml"}));
static_assert(wx::parent_is("C:/x/y.yaml", "C:\\x"));
static_assert(wx::is_absolute("C:/x/y.yaml") == true);
// 'c:\\X'
static_assert(wx::str_is("c:\\X", "c:\\X"));
static_assert(wx::name_is("c:\\X", "X"));
static_assert(wx::stem_is("c:\\X", "X"));
static_assert(wx::suffix_is("c:\\X", ""));
static_assert(wx::suffixes_are("c:\\X", {}));
static_assert(wx::parts_are("c:\\X", {"c:\\", "X"}));
static_assert(wx::parent_is("c:\\X", "c:\\"));
static_assert(wx::is_absolute("c:\\X") == true);
// 'C:'
static_assert(wx::str_is("C:", "C:"));
static_assert(wx::name_is("C:", ""));
static_assert(wx::stem_is("C:", ""));
static_assert(wx::suffix_is("C:", ""));
static_assert(wx::suffixes_are("C:", {}));
static_assert(wx::parts_are("C:", {"C:"}));
static_assert(wx::parent_is("C:", "C:"));
static_assert(wx::is_absolute("C:") == false);
// 'C:x'
static_assert(wx::str_is("C:x", "C:x"));
static_assert(wx::name_is("C:x", "x"));
static_assert(wx::stem_is("C:x", "x"));
static_assert(wx::suffix_is("C:x", ""));
static_assert(wx::suffixes_are("C:x", {}));
static_assert(wx::parts_are("C:x", {"C:", "x"}));
static_assert(wx::parent_is("C:x", "C:"));
static_assert(wx::is_absolute("C:x") == false);
// 'C:\\\\'
static_assert(wx::str_is("C:\\\\", "C:\\"));
static_assert(wx::name_is("C:\\\\", ""));
static_assert(wx::stem_is("C:\\\\", ""));
static_assert(wx::suffix_is("C:\\\\", ""));
static_assert(wx::suffixes_are("C:\\\\", {}));
static_assert(wx::parts_are("C:\\\\", {"C:\\"}));
static_assert(wx::parent_is("C:\\\\", "C:\\"));
static_assert(wx::is_absolute("C:\\\\") == true);
// '\\x\\y'
static_assert(wx::str_is("\\x\\y", "\\x\\y"));
static_assert(wx::name_is("\\x\\y", "y"));
static_assert(wx::stem_is("\\x\\y", "y"));
static_assert(wx::suffix_is("\\x\\y", ""));
static_assert(wx::suffixes_are("\\x\\y", {}));
static_assert(wx::parts_are("\\x\\y", {"\\", "x", "y"}));
static_assert(wx::parent_is("\\x\\y", "\\x"));
static_assert(wx::is_absolute("\\x\\y") == false);
// '\\\\srv\\share\\x.toml'
static_assert(wx::str_is("\\\\srv\\share\\x.toml", "\\\\srv\\share\\x.toml"));
static_assert(wx::name_is("\\\\srv\\share\\x.toml", "x.toml"));
static_assert(wx::stem_is("\\\\srv\\share\\x.toml", "x"));
static_assert(wx::suffix_is("\\\\srv\\share\\x.toml", ".toml"));
static_assert(wx::suffixes_are("\\\\srv\\share\\x.toml", {".toml"}));
static_assert(wx::parts_are("\\\\srv\\share\\x.toml", {"\\\\srv\\share\\", "x.toml"}));
static_assert(wx::parent_is("\\\\srv\\share\\x.toml", "\\\\srv\\share\\"));
static_assert(wx::is_absolute("\\\\srv\\share\\x.toml") == true);
// '\\\\srv\\share'
static_assert(wx::str_is("\\\\srv\\share", "\\\\srv\\share\\"));
static_assert(wx::name_is("\\\\srv\\share", ""));
static_assert(wx::stem_is("\\\\srv\\share", ""));
static_assert(wx::suffix_is("\\\\srv\\share", ""));
static_assert(wx::suffixes_are("\\\\srv\\share", {}));
static_assert(wx::parts_are("\\\\srv\\share", {"\\\\srv\\share\\"}));
static_assert(wx::parent_is("\\\\srv\\share", "\\\\srv\\share\\"));
static_assert(wx::is_absolute("\\\\srv\\share") == true);
// '//srv/share/x'
static_assert(wx::str_is("//srv/share/x", "\\\\srv\\share\\x"));
static_assert(wx::name_is("//srv/share/x", "x"));
static_assert(wx::stem_is("//srv/share/x", "x"));
static_assert(wx::suffix_is("//srv/share/x", ""));
static_assert(wx::suffixes_are("//srv/share/x", {}));
static_assert(wx::parts_are("//srv/share/x", {"\\\\srv\\share\\", "x"}));
static_assert(wx::parent_is("//srv/share/x", "\\\\srv\\share\\"));
static_assert(wx::is_absolute("//srv/share/x") == true);
// 'D:\\a\\b\\..\\c'
static_assert(wx::str_is("D:\\a\\b\\..\\c", "D:\\a\\b\\..\\c"));
static_assert(wx::name_is("D:\\a\\b\\..\\c", "c"));
static_assert(wx::stem_is("D:\\a\\b\\..\\c", "c"));
static_assert(wx::suffix_is("D:\\a\\b\\..\\c", ""));
static_assert(wx::suffixes_are("D:\\a\\b\\..\\c", {}));
static_assert(wx::parts_are("D:\\a\\b\\..\\c", {"D:\\", "a", "b", "..", "c"}));
static_assert(wx::parent_is("D:\\a\\b\\..\\c", "D:\\a\\b\\.."));
static_assert(wx::is_absolute("D:\\a\\b\\..\\c") == true);
// 'C:\\a b\\c.json'
static_assert(wx::str_is("C:\\a b\\c.json", "C:\\a b\\c.json"));
static_assert(wx::name_is("C:\\a b\\c.json", "c.json"));
static_assert(wx::stem_is("C:\\a b\\c.json", "c"));
static_assert(wx::suffix_is("C:\\a b\\c.json", ".json"));
static_assert(wx::suffixes_are("C:\\a b\\c.json", {".json"}));
static_assert(wx::parts_are("C:\\a b\\c.json", {"C:\\", "a b", "c.json"}));
static_assert(wx::parent_is("C:\\a b\\c.json", "C:\\a b"));
static_assert(wx::is_absolute("C:\\a b\\c.json") == true);
// 'C://x'
static_assert(wx::str_is("C://x", "C:\\x"));
static_assert(wx::name_is("C://x", "x"));
static_assert(wx::stem_is("C://x", "x"));
static_assert(wx::suffix_is("C://x", ""));
static_assert(wx::suffixes_are("C://x", {}));
static_assert(wx::parts_are("C://x", {"C:\\", "x"}));
static_assert(wx::parent_is("C://x", "C:\\"));
static_assert(wx::is_absolute("C://x") == true);
// joining
static_assert(wx::joined_is("a/b", "c", "a\\b\\c"));
static_assert(wx::rjoined_is("a/b", "c", "c\\a\\b"));
static_assert(wx::joined_is("a/b", "/x", "\\x"));
static_assert(wx::rjoined_is("a/b", "/x", "\\x\\a\\b"));
static_assert(wx::joined_is("/a/b", "c/d", "\\a\\b\\c\\d"));
static_assert(wx::rjoined_is("/a/b", "c/d", "\\a\\b"));
static_assert(wx::joined_is("", "x", "x"));
static_assert(wx::rjoined_is("", "x", "x"));
static_assert(wx::joined_is("a", "b/c/", "a\\b\\c"));
static_assert(wx::rjoined_is("a", "b/c/", "b\\c\\a"));
static_assert(wx::joined_is("/", "x", "\\x"));
static_assert(wx::rjoined_is("/", "x", "\\"));
static_assert(wx::joined_is("a/b", "", "a\\b"));
static_assert(wx::rjoined_is("a/b", "", "a\\b"));
static_assert(wx::joined_is("a/b", ".", "a\\b"));
static_assert(wx::rjoined_is("a/b", ".", "a\\b"));
static_assert(wx::joined_is("a/b", "..", "a\\b\\.."));
static_assert(wx::rjoined_is("a/b", "..", "..\\a\\b"));
static_assert(wx::joined_is("a//b", "c//d", "a\\b\\c\\d"));
static_assert(wx::rjoined_is("a//b", "c//d", "c\\d\\a\\b"));
static_assert(wx::joined_is("/a", "/", "\\"));
static_assert(wx::rjoined_is("/a", "/", "\\a"));
static_assert(wx::joined_is("x", "y/../z", "x\\y\\..\\z"));
static_assert(wx::rjoined_is("x", "y/../z", "y\\..\\z\\x"));
static_assert(wx::joined_is("spa ce", "f g", "spa ce\\f g"));
static_assert(wx::rjoined_is("spa ce", "f g", "f g\\spa ce"));
static_assert(wx::joined_is("C:\\a", "b", "C:\\a\\b"));
static_assert(wx::rjoined_is("C:\\a", "b", "C:\\a"));
static_assert(wx::joined_is("C:\\a", "\\x", "C:\\x"));
static_assert(wx::rjoined_is("C:\\a", "\\x", "C:\\a"));
static_assert(wx::joined_is("C:\\a", "D:x", "D:x"));
static_assert(wx::rjoined_is("C:\\a", "D:x", "C:\\a"));
static_assert(wx::joined_is("C:\\a", "C:x", "C:\\a\\x"));
static_assert(wx::rjoined_is("C:\\a", "C:x", "C:\\a"));
static_assert(wx::joined_is("C:\\a", "\\\\srv\\s\\y", "\\\\srv\\s\\y"));
static_assert(wx::rjoined_is("C:\\a", "\\\\srv\\s\\y", "C:\\a"));
static_assert(wx::joined_is("a", "b", "a\\b"));
static_assert(wx::rjoined_is("a", "b", "b\\a"));
static_assert(wx::joined_is("C:\\a", "D:/x", "D:\\x"));
static_assert(wx::rjoined_is("C:\\a", "D:/x", "C:\\a"));
static_assert(wx::joined_is("\\\\srv\\share\\x", "y", "\\\\srv\\share\\x\\y"));
static_assert(wx::rjoined_is("\\\\srv\\share\\x", "y", "\\\\srv\\share\\x"));
static_assert(wx::joined_is("\\\\srv\\share\\x", "\\y", "\\\\srv\\share\\y"));
static_assert(wx::rjoined_is("\\\\srv\\share\\x", "\\y", "\\\\srv\\share\\x"));
static_assert(wx::joined_is("C:", "x", "C:x"));
static_assert(wx::rjoined_is("C:", "x", "C:"));
static_assert(wx::joined_is("C:\\", "x", "C:\\x"));
static_assert(wx::rjoined_is("C:\\", "x", "C:\\"));
// with_name / with_suffix / with_stem
static_assert(wx::with_name_is("a/b.yaml", "z.txt", "a\\z.txt"));
static_assert(wx::with_name_is("a/b.yaml", "..", "a\\.."));
static_assert(wx::with_name_is("x", "y.z", "y.z"));
static_assert(wx::with_suffix_is("a/b.yaml", ".json", "a\\b.json"));
static_assert(wx::with_suffix_is("a/b.tar.gz", ".bz2", "a\\b.tar.bz2"));
static_assert(wx::with_suffix_is("a/b.tar.gz", "", "a\\b.tar"));
static_assert(wx::with_suffix_is("no_ext", ".txt", "no_ext.txt"));
static_assert(wx::with_stem_is("a/b.yaml", "q", "a\\q.yaml"));
static_assert(wx::with_stem_is("a/b.tar.gz", "q", "a\\q.gz"));

[[maybe_unused]] constexpr bool kParityProofsCompiled = true;

}  // namespace
